Cleanup things a bit

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,26 +45,29 @@ jobs:
           clangFormatVersion: 17
           inplace: true
 
-      - name: Checkout pr
-        if: ${{ github.event_name == 'pull_request' }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh pr checkout ${{ github.event.pull_request.number }}
-
       - name: Push if needed
         if: ${{ github.event_name == 'pull_request' }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           if ! git diff --exit-code; then
+            gh pr checkout ${{ github.event.pull_request.number }};
             git config user.name 'github-actions[bot]';
             git config user.email '41898282+github-actions[bot]@users.noreply.github.com';
             git add .;
             git commit -m "[skip ci] Fix code formatting";
-            git push;
+            retries=0;
+            while ! git push; do
+              echo "::warning::Failed to push the formatting changes to PR #${{ github.event.pull_request.number }} (retr:$retries)";
+              sleep 12s;
+              if [ $((retries++)) -gt 10]; then
+                echo "::error::Pushing failed after 10 retries";
+                exit 1;
+              fi
+            fi
           fi
-      - name: Show diff
+
+      - name: Show diff if needed
         if: ${{ github.event_name != 'pull_request' }}
         run: git diff --exit-code;
 
